nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
