security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        swimmers_provider:
            entity:
                class: App\Entity\Swimmer
                property: email

        admins_provider:
            entity:
                class: App\Entity\Admin
                property: email

        coaches_provider:
            entity:
                class: App\Entity\Coach
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login
            stateless: true
            provider: admins_provider 
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        admin_login:
            pattern: ^/admin/login
            stateless: true
            provider: admins_provider 
            json_login:
                check_path: /admin/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/(api|swimmer|coach)
            stateless: true
            provider: swimmers_provider 
            jwt: ~

        admin:
            pattern: ^/admin
            stateless: true
            provider: admins_provider 
            jwt: ~

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/complete-registration, roles: ROLE_USER }
        - { path: ^/swimmer/change-password, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/coach, roles: ROLE_COACH }
